name = "loansbazaar-website"
main = "worker.js"
compatibility_date = "2026-09-15"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "LOANSBAZAAR_DB"
database_name = "loansbazaar-db"
database_id = "e8049730-c319-4045-ad37-f4910302e716"
